# Generated by Django 5.1.4 on 2025-08-01 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("security", "0002_audit_trail"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SecurityAudit",
        ),
    ]
