# Generated by Django 5.1.4 on 2025-07-15 00:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="session_fingerprint",
        ),
        migrations.AddField(
            model_name="user",
            name="account_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="default_currency",
            field=models.CharField(
                choices=[
                    ("BTC", "Bitcoin"),
                    ("XMR", "Monero"),
                    ("LTC", "Litecoin"),
                    ("USDT", "Tether"),
                ],
                default="XMR",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="default_shipping_country",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="feedback_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="user",
            name="pgp_challenge",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="pgp_challenge_expires",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="pgp_fingerprint",
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AddField(
            model_name="user",
            name="pgp_login_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="positive_feedback_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="session_fingerprints",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="user",
            name="total_trades",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="user",
            name="panic_password",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="LoginHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("login_time", models.DateTimeField(auto_now_add=True)),
                ("ip_hash", models.CharField(max_length=64)),
                ("user_agent", models.CharField(max_length=200)),
                ("success", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-login_time"],
            },
        ),
    ]
