# Generated by Django 5.1.4 on 2025-07-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0002_remove_user_session_fingerprint_user_account_created_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="theme_preference",
            field=models.CharField(
                choices=[("classic", "Classic Dark"), ("premium", "Premium Glass")],
                default="classic",
                max_length=20,
            ),
        ),
    ]
