# Generated by Django 5.1.4 on 2025-07-15 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_theme_preference"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="theme_preference",
        ),
    ]
