# Generated by Django 5.1.4 on 2025-07-16 21:54

from django.db import migrations, models


def migrate_currency_choices(apps, schema_editor):
    """Migrate existing users with LTC/USDT to BTC"""
    User = apps.get_model('accounts', 'User')
    User.objects.filter(default_currency__in=['LTC', 'USDT']).update(default_currency='BTC')


def reverse_migrate_currency_choices(apps, schema_editor):
    """Reverse migration - no action needed as we can't restore original values"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_theme_preference"),
    ]

    operations = [
        migrations.RunPython(migrate_currency_choices, reverse_migrate_currency_choices),
        migrations.AlterField(
            model_name="user",
            name="default_currency",
            field=models.CharField(
                choices=[
                    ("BTC", "Bitcoin"),
                    ("XMR", "Monero"),
                    ("USD", "USD"),
                    ("EUR", "Euro"),
                ],
                default="BTC",
                max_length=10,
            ),
        ),
    ]
