# Generated by Django 5.1.4 on 2025-09-10 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_update_currency_choices"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserSession",
        ),
    ]
