# Generated by Django 5.1.4 on 2025-07-24 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_add_totp_fields"),
        ("accounts", "0005_update_currency_choices"),
    ]

    operations = []
