# Generated by Django 5.1.4 on 2025-07-24 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_merge_20250724_0412"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="last_totp_failure",
        ),
        migrations.RemoveField(
            model_name="user",
            name="totp_backup_codes",
        ),
        migrations.RemoveField(
            model_name="user",
            name="totp_enabled",
        ),
        migrations.RemoveField(
            model_name="user",
            name="totp_failure_count",
        ),
        migrations.RemoveField(
            model_name="user",
            name="totp_secret",
        ),
    ]
