# Generated by Django 5.1.4 on 2025-07-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_remove_user_last_totp_failure_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="totp_backup_codes",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="user",
            name="totp_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="totp_last_used_counter",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="totp_secret",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
