# Generated by Django 5.1.4 on 2025-07-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_user_totp_backup_codes_user_totp_enabled_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="totp_secret",
            field=models.TextField(blank=True, null=True),
        ),
    ]
