# Generated by Django 5.1.4 on 2025-08-07 11:03

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0002_alter_withdrawalrequest_address_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wallet",
            name="escrow_btc",
            field=models.DecimalField(
                decimal_places=8, default=Decimal("0"), max_digits=18
            ),
        ),
        migrations.AddField(
            model_name="wallet",
            name="escrow_xmr",
            field=models.DecimalField(
                decimal_places=12, default=Decimal("0"), max_digits=18
            ),
        ),
        migrations.AddField(
            model_name="wallet",
            name="last_activity",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="wallet",
            name="two_fa_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="wallet",
            name="two_fa_secret",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="wallet",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="wallet",
            name="withdrawal_pin",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="withdrawalrequest",
            name="admin_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="withdrawalrequest",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="withdrawalrequest",
            name="manual_review_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="withdrawalrequest",
            name="pin_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="withdrawalrequest",
            name="processed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processed_withdrawals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="withdrawalrequest",
            name="risk_factors",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="withdrawalrequest",
            name="risk_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="withdrawalrequest",
            name="two_fa_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="withdrawalrequest",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="withdrawalrequest",
            name="user_agent",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="withdrawalrequest",
            name="user_note",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="withdrawalrequest",
            name="currency",
            field=models.CharField(
                choices=[("btc", "Bitcoin"), ("xmr", "Monero")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="withdrawalrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("reviewing", "Under Review"),
                    ("approved", "Approved"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("rejected", "Rejected"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ConversionRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_currency", models.CharField(max_length=3)),
                ("to_currency", models.CharField(max_length=3)),
                ("rate", models.DecimalField(decimal_places=12, max_digits=20)),
                ("source", models.CharField(default="manual", max_length=50)),
                ("source_data", models.JSONField(blank=True, default=dict)),
                ("valid_from", models.DateTimeField(default=django.utils.timezone.now)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["from_currency", "to_currency", "is_active"],
                        name="wallets_con_from_cu_044657_idx",
                    ),
                    models.Index(
                        fields=["valid_from", "valid_until"],
                        name="wallets_con_valid_f_1dc20a_idx",
                    ),
                ],
                "unique_together": {("from_currency", "to_currency", "valid_from")},
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("withdrawal_request", "Withdrawal Request"),
                            ("withdrawal_approved", "Withdrawal Approved"),
                            ("withdrawal_rejected", "Withdrawal Rejected"),
                            ("withdrawal_cancelled", "Withdrawal Cancelled"),
                            ("conversion", "Currency Conversion"),
                            ("settings_change", "Settings Change"),
                            ("security_alert", "Security Alert"),
                            ("admin_action", "Admin Action"),
                        ],
                        max_length=50,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField()),
                ("details", models.JSONField(default=dict)),
                ("risk_score", models.IntegerField(default=0)),
                ("flagged", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "action", "created_at"],
                        name="wallets_aud_user_id_cd4a95_idx",
                    ),
                    models.Index(
                        fields=["flagged", "risk_score"],
                        name="wallets_aud_flagged_858ccc_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("deposit", "Deposit"),
                            ("withdrawal", "Withdrawal"),
                            ("conversion", "Conversion"),
                            ("escrow_lock", "Escrow Lock"),
                            ("escrow_release", "Escrow Release"),
                            ("escrow_refund", "Escrow Refund"),
                            ("fee", "Fee"),
                            ("adjustment", "Adjustment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=12, max_digits=18)),
                ("currency", models.CharField(max_length=3)),
                (
                    "converted_amount",
                    models.DecimalField(
                        blank=True, decimal_places=12, max_digits=18, null=True
                    ),
                ),
                (
                    "converted_currency",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                (
                    "conversion_rate",
                    models.DecimalField(
                        blank=True, decimal_places=12, max_digits=20, null=True
                    ),
                ),
                (
                    "balance_before",
                    models.DecimalField(decimal_places=12, max_digits=18),
                ),
                (
                    "balance_after",
                    models.DecimalField(decimal_places=12, max_digits=18),
                ),
                ("reference", models.CharField(db_index=True, max_length=255)),
                (
                    "related_object_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("related_object_id", models.IntegerField(blank=True, null=True)),
                ("transaction_hash", models.CharField(max_length=64, unique=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "type", "created_at"],
                        name="wallets_tra_user_id_93760e_idx",
                    ),
                    models.Index(
                        fields=["reference"], name="wallets_tra_referen_6d0dd5_idx"
                    ),
                    models.Index(
                        fields=["transaction_hash"],
                        name="wallets_tra_transac_e0f8cc_idx",
                    ),
                ],
            },
        ),
    ]
