# Generated by Django 5.1.4 on 2025-07-23 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0002_wallet_system_rewrite"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auditlog",
            name="ip_address",
        ),
        migrations.RemoveField(
            model_name="auditlog",
            name="user_agent",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="ip_address",
        ),
        migrations.RemoveField(
            model_name="withdrawalrequest",
            name="ip_address",
        ),
        migrations.RemoveField(
            model_name="withdrawalrequest",
            name="user_agent",
        ),
    ]
