# Generated by Django 5.1.4 on 2025-07-27 08:31

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0003_remove_auditlog_ip_address_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auditlog",
            name="user",
        ),
        migrations.DeleteModel(
            name="ConversionRate",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="user",
        ),
        migrations.RemoveField(
            model_name="walletbalancecheck",
            name="resolved_by",
        ),
        migrations.RemoveField(
            model_name="walletbalancecheck",
            name="wallet",
        ),
        migrations.AlterModelOptions(
            name="withdrawalrequest",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="wallet",
            name="wallets_wal_user_id_c74908_idx",
        ),
        migrations.RemoveIndex(
            model_name="withdrawalrequest",
            name="wallets_wit_user_id_b41185_idx",
        ),
        migrations.RemoveIndex(
            model_name="withdrawalrequest",
            name="wallets_wit_status_8c35ac_idx",
        ),
        migrations.RenameField(
            model_name="withdrawalrequest",
            old_name="processed_at",
            new_name="approved_at",
        ),
        migrations.RemoveField(
            model_name="wallet",
            name="balance_btc",
        ),
        migrations.RemoveField(
            model_name="wallet",
            name="balance_xmr",
        ),
        migrations.RemoveField(
            model_name="wallet",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="wallet",
            name="daily_withdrawal_limit_btc",
        ),
        migrations.RemoveField(
            model_name="wallet",
            name="daily_withdrawal_limit_xmr",
        ),
        migrations.RemoveField(
            model_name="wallet",
            name="escrow_btc",
        ),
        migrations.RemoveField(
            model_name="wallet",
            name="escrow_xmr",
        ),
        migrations.RemoveField(
            model_name="wallet",
            name="last_activity",
        ),
        migrations.RemoveField(
            model_name="wallet",
            name="two_fa_enabled",
        ),
        migrations.RemoveField(
            model_name="wallet",
            name="two_fa_secret",
        ),
        migrations.RemoveField(
            model_name="wallet",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="wallet",
            name="withdrawal_pin",
        ),
        migrations.RemoveField(
            model_name="withdrawalrequest",
            name="admin_notes",
        ),
        migrations.RemoveField(
            model_name="withdrawalrequest",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="withdrawalrequest",
            name="manual_review_required",
        ),
        migrations.RemoveField(
            model_name="withdrawalrequest",
            name="pin_verified",
        ),
        migrations.RemoveField(
            model_name="withdrawalrequest",
            name="processed_by",
        ),
        migrations.RemoveField(
            model_name="withdrawalrequest",
            name="risk_factors",
        ),
        migrations.RemoveField(
            model_name="withdrawalrequest",
            name="risk_score",
        ),
        migrations.RemoveField(
            model_name="withdrawalrequest",
            name="two_fa_verified",
        ),
        migrations.RemoveField(
            model_name="withdrawalrequest",
            name="tx_fee",
        ),
        migrations.RemoveField(
            model_name="withdrawalrequest",
            name="tx_hash",
        ),
        migrations.RemoveField(
            model_name="withdrawalrequest",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="withdrawalrequest",
            name="user_note",
        ),
        migrations.AddField(
            model_name="wallet",
            name="balance",
            field=models.DecimalField(
                decimal_places=8, default=Decimal("0E-8"), max_digits=18
            ),
        ),
        migrations.AddField(
            model_name="withdrawalrequest",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_withdrawals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="withdrawalrequest",
            name="address",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="withdrawalrequest",
            name="amount",
            field=models.DecimalField(decimal_places=8, max_digits=18),
        ),
        migrations.AlterField(
            model_name="withdrawalrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="withdrawalrequest",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="AuditLog",
        ),
        migrations.DeleteModel(
            name="Transaction",
        ),
        migrations.DeleteModel(
            name="WalletBalanceCheck",
        ),
    ]
