# Generated by Django 5.1.4 on 2025-08-01 22:29

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("vendor_name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "total_sales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "rating",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                ("is_approved", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("low_stock_threshold", models.IntegerField(default=5)),
                ("response_time", models.DurationField(blank=True, null=True)),
                ("vacation_mode", models.BooleanField(default=False)),
                ("vacation_message", models.TextField(blank=True)),
                ("vacation_started", models.DateTimeField(blank=True, null=True)),
                ("vacation_ends", models.DateTimeField(blank=True, null=True)),
                ("pgp_key", models.TextField(blank=True, null=True)),
                ("bond_paid", models.BooleanField(default=False)),
                (
                    "bond_amount",
                    models.DecimalField(decimal_places=8, default=0.0, max_digits=20),
                ),
                (
                    "bond_currency",
                    models.CharField(
                        choices=[("BTC", "Bitcoin"), ("XMR", "Monero")],
                        default="BTC",
                        max_length=3,
                    ),
                ),
                (
                    "bond_transaction_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("trust_score", models.IntegerField(default=0)),
                ("trust_level", models.CharField(default="new", max_length=20)),
                ("trust_factors", models.JSONField(blank=True, default=dict)),
                ("trust_updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubVendor",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("can_view_orders", models.BooleanField(default=True)),
                ("can_respond_messages", models.BooleanField(default=True)),
                ("can_update_tracking", models.BooleanField(default=False)),
                ("can_process_refunds", models.BooleanField(default=False)),
                ("daily_message_limit", models.IntegerField(default=100)),
                ("messages_sent_today", models.IntegerField(default=0)),
                (
                    "last_message_reset",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_subvendors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_vendor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "main_vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_vendors",
                        to="vendors.vendor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Promotion",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "discount_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("max_uses", models.IntegerField(default=100)),
                ("current_uses", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotions",
                        to="vendors.vendor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "1 Star"),
                            (2, "2 Stars"),
                            (3, "3 Stars"),
                            (4, "4 Stars"),
                            (5, "5 Stars"),
                        ]
                    ),
                ),
                ("comment", models.TextField()),
                ("vendor_response", models.TextField(blank=True)),
                ("response_date", models.DateTimeField(blank=True, null=True)),
                ("is_public", models.BooleanField(default=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="given_feedback",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="vendors.vendor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VendorNotification",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("low_stock", "Low Stock Alert"),
                            ("new_order", "New Order"),
                            ("new_feedback", "New Feedback"),
                            ("promotion_expiry", "Promotion Expiring"),
                            ("system", "System Notification"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VendorRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="vendors.vendor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubVendorActivityLog",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("account_created", "Account Created"),
                            ("account_deactivated", "Account Deactivated"),
                            ("permissions_updated", "Permissions Updated"),
                            ("order_viewed", "Order Viewed"),
                            ("message_sent", "Message Sent"),
                            ("tracking_updated", "Tracking Updated"),
                            ("refund_processed", "Refund Processed"),
                            ("login", "Login"),
                        ],
                        max_length=30,
                    ),
                ),
                ("details", models.JSONField(default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "sub_vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to="vendors.subvendor",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["sub_vendor", "-created_at"],
                        name="vendors_sub_sub_ven_17c3ed_idx",
                    ),
                    models.Index(
                        fields=["action"], name="vendors_sub_action_9a08c8_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="vendor",
            index=models.Index(
                fields=["is_approved", "is_active"],
                name="vendors_ven_is_appr_ebcbe2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="vendor",
            index=models.Index(
                fields=["trust_level"], name="vendors_ven_trust_l_c6d6eb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendor",
            index=models.Index(fields=["rating"], name="vendors_ven_rating_1e84ed_idx"),
        ),
        migrations.AddIndex(
            model_name="vendor",
            index=models.Index(
                fields=["vacation_mode"], name="vendors_ven_vacatio_037ffd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subvendor",
            index=models.Index(
                fields=["main_vendor", "is_active"],
                name="vendors_sub_main_ve_9ece3a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="subvendor",
            index=models.Index(fields=["user"], name="vendors_sub_user_id_ed8594_idx"),
        ),
        migrations.AddIndex(
            model_name="promotion",
            index=models.Index(fields=["code"], name="vendors_pro_code_737161_idx"),
        ),
        migrations.AddIndex(
            model_name="promotion",
            index=models.Index(
                fields=["vendor", "is_active"], name="vendors_pro_vendor__dfe3bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="promotion",
            index=models.Index(
                fields=["start_date", "end_date"], name="vendors_pro_start_d_8f53f8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(
                fields=["vendor", "is_public"], name="vendors_fee_vendor__748d82_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(fields=["rating"], name="vendors_fee_rating_e50b78_idx"),
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(
                fields=["-created_at"], name="vendors_fee_created_1d959a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendornotification",
            index=models.Index(
                fields=["vendor", "is_read"], name="vendors_ven_vendor__246df2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendornotification",
            index=models.Index(
                fields=["notification_type"], name="vendors_ven_notific_f51178_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendornotification",
            index=models.Index(
                fields=["-created_at"], name="vendors_ven_created_999ab5_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="vendorrating",
            unique_together={("vendor", "user")},
        ),
    ]
