# Generated by Django 5.1.4 on 2025-07-17 20:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "1 Star"),
                            (2, "2 Stars"),
                            (3, "3 Stars"),
                            (4, "4 Stars"),
                            (5, "5 Stars"),
                        ]
                    ),
                ),
                ("comment", models.TextField()),
                ("vendor_response", models.TextField(blank=True)),
                ("response_date", models.DateTimeField(blank=True, null=True)),
                ("is_public", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Promotion",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "discount_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("max_uses", models.IntegerField(default=100)),
                ("current_uses", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="VendorNotification",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("low_stock", "Low Stock Alert"),
                            ("new_order", "New Order"),
                            ("new_feedback", "New Feedback"),
                            ("promotion_expiry", "Promotion Expiring"),
                            ("system", "System Notification"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="vendor",
            name="low_stock_threshold",
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name="vendor",
            name="response_time",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="vendor",
            index=models.Index(
                fields=["is_approved", "is_active"],
                name="vendors_ven_is_appr_ebcbe2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="vendor",
            index=models.Index(
                fields=["trust_level"], name="vendors_ven_trust_l_c6d6eb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendor",
            index=models.Index(fields=["rating"], name="vendors_ven_rating_1e84ed_idx"),
        ),
        migrations.AddField(
            model_name="feedback",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="given_feedback",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback",
                to="vendors.vendor",
            ),
        ),
        migrations.AddField(
            model_name="promotion",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="promotions",
                to="vendors.vendor",
            ),
        ),
        migrations.AddField(
            model_name="vendornotification",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="vendors.vendor",
            ),
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(
                fields=["vendor", "is_public"], name="vendors_fee_vendor__748d82_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(fields=["rating"], name="vendors_fee_rating_e50b78_idx"),
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(
                fields=["-created_at"], name="vendors_fee_created_1d959a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="promotion",
            index=models.Index(fields=["code"], name="vendors_pro_code_737161_idx"),
        ),
        migrations.AddIndex(
            model_name="promotion",
            index=models.Index(
                fields=["vendor", "is_active"], name="vendors_pro_vendor__dfe3bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="promotion",
            index=models.Index(
                fields=["start_date", "end_date"], name="vendors_pro_start_d_8f53f8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendornotification",
            index=models.Index(
                fields=["vendor", "is_read"], name="vendors_ven_vendor__246df2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendornotification",
            index=models.Index(
                fields=["notification_type"], name="vendors_ven_notific_f51178_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendornotification",
            index=models.Index(
                fields=["-created_at"], name="vendors_ven_created_999ab5_idx"
            ),
        ),
    ]
