# Generated by Django 5.1.4 on 2025-07-18 12:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0002_feedback_promotion_vendornotification_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubVendor",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("can_view_orders", models.BooleanField(default=True)),
                ("can_respond_messages", models.BooleanField(default=True)),
                ("can_update_tracking", models.BooleanField(default=False)),
                ("can_process_refunds", models.BooleanField(default=False)),
                ("daily_message_limit", models.IntegerField(default=100)),
                ("messages_sent_today", models.IntegerField(default=0)),
                (
                    "last_message_reset",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SubVendorActivityLog",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("account_created", "Account Created"),
                            ("account_deactivated", "Account Deactivated"),
                            ("permissions_updated", "Permissions Updated"),
                            ("order_viewed", "Order Viewed"),
                            ("message_sent", "Message Sent"),
                            ("tracking_updated", "Tracking Updated"),
                            ("refund_processed", "Refund Processed"),
                            ("login", "Login"),
                        ],
                        max_length=30,
                    ),
                ),
                ("details", models.JSONField(default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="vendor",
            name="vacation_ends",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vendor",
            name="vacation_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="vendor",
            name="vacation_mode",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vendor",
            name="vacation_started",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="vendor",
            index=models.Index(
                fields=["vacation_mode"], name="vendors_ven_vacatio_037ffd_idx"
            ),
        ),
        migrations.AddField(
            model_name="subvendor",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_subvendors",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="subvendor",
            name="main_vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_vendors",
                to="vendors.vendor",
            ),
        ),
        migrations.AddField(
            model_name="subvendor",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_vendor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="subvendoractivitylog",
            name="sub_vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_logs",
                to="vendors.subvendor",
            ),
        ),
        migrations.AddIndex(
            model_name="subvendor",
            index=models.Index(
                fields=["main_vendor", "is_active"],
                name="vendors_sub_main_ve_9ece3a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="subvendor",
            index=models.Index(fields=["user"], name="vendors_sub_user_id_ed8594_idx"),
        ),
        migrations.AddIndex(
            model_name="subvendoractivitylog",
            index=models.Index(
                fields=["sub_vendor", "-created_at"],
                name="vendors_sub_sub_ven_17c3ed_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="subvendoractivitylog",
            index=models.Index(fields=["action"], name="vendors_sub_action_9a08c8_idx"),
        ),
    ]
