# Generated by Django 5.1.4 on 2025-07-18 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "vendors",
            "0003_subvendor_subvendoractivitylog_vendor_vacation_ends_and_more",
        ),
    ]

    operations = []
