# Generated by Django 5.1.4 on 2025-07-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0004_add_vacation_and_subvendor_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="bond_amount",
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name="vendor",
            name="bond_currency",
            field=models.CharField(
                choices=[("BTC", "Bitcoin"), ("XMR", "Monero")],
                default="BTC",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="bond_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vendor",
            name="bond_transaction_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="vendor",
            name="pgp_key",
            field=models.TextField(blank=True, null=True),
        ),
    ]
