# Generated by Django 5.1.4 on 2025-07-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0005_vendor_bond_amount_vendor_bond_currency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="trust_factors",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="vendor",
            name="trust_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="vendor",
            name="trust_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="trust_level",
            field=models.CharField(default="new", max_length=20),
        ),
    ]
