# Generated by Django 5.1.4 on 2025-07-22 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
        ("wallets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="buyer_wallet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buyer_orders",
                to="wallets.wallet",
            ),
        ),
    ]
