# Generated by Django 5.1.4 on 2025-07-18 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image_filename",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="product",
            name="thumbnail_filename",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
