# Generated by Django 5.1.4 on 2025-07-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_image_filename_product_thumbnail_filename"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="was_active_before_vacation",
            field=models.BooleanField(default=False),
        ),
    ]
