# Generated by Django 5.1.4 on 2025-07-18 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_was_active_before_vacation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="was_active_before_vacation",
        ),
    ]
