# Generated by Django 5.1.4 on 2025-09-10 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_remove_vacation_field"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProductImage",
        ),
    ]
